#!/usr/bin/env bash
# Launch an agent CLI inside the agents container.
# Usage: run.sh <agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|cursor-agent|codegraph|clipboard-bridge|bash> [args...]

set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$AGENTS_DIR/docker-compose.yml"
SERVICE="agents"

# Keep AGENTS_DIR in .env so compose can interpolate Hermes docker_volumes
if [[ -f "$AGENTS_DIR/.env" ]]; then
  if grep -q '^AGENTS_DIR=' "$AGENTS_DIR/.env" 2>/dev/null; then
    tmp="$(mktemp)"
    sed "s|^AGENTS_DIR=.*|AGENTS_DIR=$AGENTS_DIR|" "$AGENTS_DIR/.env" > "$tmp"
    mv "$tmp" "$AGENTS_DIR/.env"
  else
    {
      printf '\n'
      printf '# Absolute path to this repo (Hermes sandbox bind mounts)\n'
      printf 'AGENTS_DIR=%s\n' "$AGENTS_DIR"
    } >> "$AGENTS_DIR/.env"
  fi
fi

# Load local .env (HOST_PROJECTS, API keys for compose)
if [[ -f "$AGENTS_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$AGENTS_DIR/.env"
  set +a
fi
# Script path wins over a stale .env value
export AGENTS_DIR

# macOS: gh OAuth lives in Keychain, not in ~/.config/gh — inject for compose.
if [[ -z "${GH_TOKEN:-}" ]] && command -v gh >/dev/null 2>&1; then
  if token="$(gh auth token 2>/dev/null)" && [[ -n "$token" ]]; then
    export GH_TOKEN="$token"
  fi
fi

# Projects root on the host (== path inside container)
HOST_PROJECTS="${HOST_PROJECTS:-$HOME/Documents/projects}"
HOST_PROJECTS="${HOST_PROJECTS/#\~/$HOME}"

# Prefer standalone docker-compose if the compose plugin is missing
if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose -f "$COMPOSE_FILE")
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose -f "$COMPOSE_FILE")
else
  echo "docker compose / docker-compose not found" >&2
  exit 1
fi

hermes_enabled() {
  case "${HERMES:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

ensure_cliproxy_config() {
  mkdir -p "$AGENTS_DIR/data/cliproxy/auths"

  if [[ -z "${CLIPROXY_API_KEY:-}" ]]; then
    CLIPROXY_API_KEY="$(openssl rand -hex 32)"
    {
      printf '\n'
      printf '# CLIProxyAPI (Claudex) — auto-generated by run.sh\n'
      printf 'CLIPROXY_API_KEY=%s\n' "$CLIPROXY_API_KEY"
    } >> "$AGENTS_DIR/.env"
    echo "note: CLIPROXY_API_KEY generiert und in .env geschrieben" >&2
  fi

  local config="$AGENTS_DIR/data/cliproxy/config.yaml"
  if [[ -f "$config" ]]; then
    return
  fi
  if [[ -f "$AGENTS_DIR/cliproxy/config.example.yaml" ]]; then
    sed "s/replace-with-CLIPROXY_API_KEY/${CLIPROXY_API_KEY}/" \
      "$AGENTS_DIR/cliproxy/config.example.yaml" > "$config"
  else
    cat > "$config" <<EOF
host: ""
port: 8317
auth-dir: "/root/.cli-proxy-api"
api-keys:
  - "${CLIPROXY_API_KEY}"
debug: false
EOF
  fi
}

ensure_services() {
  ensure_cliproxy_config
  mkdir -p "$AGENTS_DIR/data/clipboard"
  if hermes_enabled; then
    mkdir -p "$AGENTS_DIR/data/hermes"
    "${COMPOSE[@]}" --profile hermes up -d --quiet-pull
  else
    "${COMPOSE[@]}" up -d --quiet-pull
  fi
}

# Host-side: mirror macOS clipboard PNGs into data/clipboard for container stubs.
ensure_clipboard_bridge() {
  [[ "$(uname -s)" == "Darwin" ]] || return 0
  mkdir -p "$AGENTS_DIR/data/clipboard"
  "$AGENTS_DIR/clipboard-bridge.sh" --daemon
}

cmd="${1:-}"
if [[ -z "$cmd" ]]; then
  echo "usage: $(basename "$0") <agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|codegraph|clipboard-bridge|bash> [args...]" >&2
  exit 1
fi
shift

case "$cmd" in
  agent|cursor-agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|codegraph|clipboard-bridge|bash) ;;
  *)
    echo "unknown command: $cmd (expected agent, pi, claude, claudex, cliproxy-login, hermes, hermes-setup, codegraph, clipboard-bridge, or bash)" >&2
    exit 1
    ;;
esac

# Host clipboard bridge (not inside the container)
if [[ "$cmd" == "clipboard-bridge" ]]; then
  exec "$AGENTS_DIR/clipboard-bridge.sh" "$@"
fi

# Same-path mount: host cwd under HOST_PROJECTS is identical in container
if [[ "$PWD" == "$HOST_PROJECTS" || "$PWD" == "$HOST_PROJECTS"/* ]]; then
  workdir="$PWD"
else
  workdir="$HOST_PROJECTS"
  echo "note: cwd is outside $HOST_PROJECTS → starting in $HOST_PROJECTS" >&2
fi

# ChatGPT / Codex OAuth for CLIProxyAPI (one-time)
if [[ "$cmd" == "cliproxy-login" ]]; then
  ensure_services
  exec "${COMPOSE[@]}" exec -it cli-proxy-api \
    /CLIProxyAPI/CLIProxyAPI -no-browser --codex-login "$@"
fi

# Claude Code harness → GPT-5.6 Sol via CLIProxyAPI (/usr/local/bin/claudex in image)
if [[ "$cmd" == "claudex" ]]; then
  if [[ -z "${CLIPROXY_API_KEY:-}" ]]; then
    echo "error: CLIPROXY_API_KEY missing in .env — run ./start.sh first" >&2
    exit 1
  fi
  ensure_services
  ensure_clipboard_bridge
  exec "${COMPOSE[@]}" exec -it -w "$workdir" \
    -e CLIPROXY_API_KEY="$CLIPROXY_API_KEY" \
    "$SERVICE" claudex "$@"
fi

# Hermes one-time setup wizard (does not require HERMES=1 / running gateway)
if [[ "$cmd" == "hermes-setup" ]]; then
  mkdir -p "$AGENTS_DIR/data/hermes"
  exec docker run -it --rm \
    -v "$AGENTS_DIR/data/hermes:/opt/data" \
    -v "${HOST_PROJECTS}:${HOST_PROJECTS}" \
    -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}" \
    -e OPENAI_API_KEY="${OPENAI_API_KEY:-}" \
    -e GOOGLE_API_KEY="${GOOGLE_API_KEY:-}" \
    -w "$workdir" \
    nousresearch/hermes-agent:latest setup "$@"
fi

# Interactive Hermes CLI against the running gateway container
if [[ "$cmd" == "hermes" ]]; then
  if ! hermes_enabled; then
    echo "error: Hermes is disabled — set HERMES=1 in .env and run ./start.sh" >&2
    exit 1
  fi
  ensure_services
  if ! docker ps --format '{{.Names}}' | grep -qx hermes; then
    echo "error: hermes container is not running — check HERMES=1 and ./start.sh" >&2
    exit 1
  fi
  exec "${COMPOSE[@]}" --profile hermes exec -it -w "$workdir" hermes hermes "$@"
fi

# Start container if needed
if ! docker ps --format '{{.Names}}' | grep -qx agents; then
  ensure_services
fi

# Screenshot paste: host bridge → xclip/wl-paste stubs (Claude + Cursor CLI).
# DISPLAY=:0 is a no-op for Claude; Cursor only probes clipboard when DISPLAY is set.
# (Avoid empty "${arr[@]}" under macOS bash 3.2 + set -u.)
case "$cmd" in
  claude|agent|cursor-agent)
    ensure_clipboard_bridge
    exec "${COMPOSE[@]}" exec -it -w "$workdir" \
      -e "DISPLAY=${DISPLAY:-:0}" \
      "$SERVICE" "$cmd" "$@"
    ;;
esac

exec "${COMPOSE[@]}" exec -it -w "$workdir" "$SERVICE" "$cmd" "$@"
