#!/usr/bin/env bash
# Launch an agent CLI inside the agents container.
# Usage: run.sh <agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|cursor-agent|codegraph|bash> [args...]

set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$AGENTS_DIR/docker-compose.yml"
SERVICE="agents"

# Load local .env (HOST_PROJECTS, API keys for compose)
if [[ -f "$AGENTS_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$AGENTS_DIR/.env"
  set +a
fi

# Projects root on the host (== path inside container)
HOST_PROJECTS="${HOST_PROJECTS:-$HOME/Documents/projects}"
HOST_PROJECTS="${HOST_PROJECTS/#\~/$HOME}"

# Prefer standalone docker-compose if the compose plugin is missing
if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose -f "$COMPOSE_FILE")
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose -f "$COMPOSE_FILE")
else
  echo "docker compose / docker-compose not found" >&2
  exit 1
fi

hermes_enabled() {
  case "${HERMES:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

ensure_cliproxy_config() {
  mkdir -p "$AGENTS_DIR/data/cliproxy/auths"

  if [[ -z "${CLIPROXY_API_KEY:-}" ]]; then
    CLIPROXY_API_KEY="$(openssl rand -hex 32)"
    {
      printf '\n'
      printf '# CLIProxyAPI (Claudex) — auto-generated by run.sh\n'
      printf 'CLIPROXY_API_KEY=%s\n' "$CLIPROXY_API_KEY"
    } >> "$AGENTS_DIR/.env"
    echo "note: CLIPROXY_API_KEY generiert und in .env geschrieben" >&2
  fi

  local config="$AGENTS_DIR/data/cliproxy/config.yaml"
  if [[ -f "$config" ]]; then
    return
  fi
  if [[ -f "$AGENTS_DIR/cliproxy/config.example.yaml" ]]; then
    sed "s/replace-with-CLIPROXY_API_KEY/${CLIPROXY_API_KEY}/" \
      "$AGENTS_DIR/cliproxy/config.example.yaml" > "$config"
  else
    cat > "$config" <<EOF
host: ""
port: 8317
auth-dir: "/root/.cli-proxy-api"
api-keys:
  - "${CLIPROXY_API_KEY}"
debug: false
EOF
  fi
}

ensure_services() {
  ensure_cliproxy_config
  if hermes_enabled; then
    mkdir -p "$AGENTS_DIR/data/hermes"
    "${COMPOSE[@]}" --profile hermes up -d --quiet-pull
  else
    "${COMPOSE[@]}" up -d --quiet-pull
  fi
}

cmd="${1:-}"
if [[ -z "$cmd" ]]; then
  echo "usage: $(basename "$0") <agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|codegraph|bash> [args...]" >&2
  exit 1
fi
shift

case "$cmd" in
  agent|cursor-agent|pi|claude|claudex|cliproxy-login|hermes|hermes-setup|codegraph|bash) ;;
  *)
    echo "unknown command: $cmd (expected agent, pi, claude, claudex, cliproxy-login, hermes, hermes-setup, codegraph, or bash)" >&2
    exit 1
    ;;
esac

# Same-path mount: host cwd under HOST_PROJECTS is identical in container
if [[ "$PWD" == "$HOST_PROJECTS" || "$PWD" == "$HOST_PROJECTS"/* ]]; then
  workdir="$PWD"
else
  workdir="$HOST_PROJECTS"
  echo "note: cwd is outside $HOST_PROJECTS → starting in $HOST_PROJECTS" >&2
fi

# ChatGPT / Codex OAuth for CLIProxyAPI (one-time)
if [[ "$cmd" == "cliproxy-login" ]]; then
  ensure_services
  exec "${COMPOSE[@]}" exec -it cli-proxy-api \
    /CLIProxyAPI/CLIProxyAPI -no-browser --codex-login "$@"
fi

# Claude Code harness → GPT-5.6 Sol via CLIProxyAPI
if [[ "$cmd" == "claudex" ]]; then
  if [[ -z "${CLIPROXY_API_KEY:-}" ]]; then
    echo "error: CLIPROXY_API_KEY missing in .env — run ./start.sh first" >&2
    exit 1
  fi
  ensure_services
  exec "${COMPOSE[@]}" exec -it -w "$workdir" \
    -e ANTHROPIC_BASE_URL=http://cli-proxy-api:8317 \
    -e ANTHROPIC_AUTH_TOKEN="$CLIPROXY_API_KEY" \
    -e ANTHROPIC_API_KEY= \
    -e CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-sol \
    -e CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
    -e CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
    -e ENABLE_TOOL_SEARCH=false \
    "$SERVICE" claude --model gpt-5.6-sol "$@"
fi

# Hermes one-time setup wizard (does not require HERMES=1 / running gateway)
if [[ "$cmd" == "hermes-setup" ]]; then
  mkdir -p "$AGENTS_DIR/data/hermes"
  exec docker run -it --rm \
    -v "$AGENTS_DIR/data/hermes:/opt/data" \
    -v "${HOST_PROJECTS}:${HOST_PROJECTS}" \
    -e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}" \
    -e OPENAI_API_KEY="${OPENAI_API_KEY:-}" \
    -e GOOGLE_API_KEY="${GOOGLE_API_KEY:-}" \
    -w "$workdir" \
    nousresearch/hermes-agent:latest setup "$@"
fi

# Interactive Hermes CLI against the running gateway container
if [[ "$cmd" == "hermes" ]]; then
  if ! hermes_enabled; then
    echo "error: Hermes is disabled — set HERMES=1 in .env and run ./start.sh" >&2
    exit 1
  fi
  ensure_services
  if ! docker ps --format '{{.Names}}' | grep -qx hermes; then
    echo "error: hermes container is not running — check HERMES=1 and ./start.sh" >&2
    exit 1
  fi
  exec "${COMPOSE[@]}" --profile hermes exec -it -w "$workdir" hermes hermes "$@"
fi

# Start container if needed
if ! docker ps --format '{{.Names}}' | grep -qx agents; then
  ensure_services
fi

exec "${COMPOSE[@]}" exec -it -w "$workdir" "$SERVICE" "$cmd" "$@"
