#!/usr/bin/env bash
# Bootstrap Docker on macOS (Colima) and start the agents container.
# Usage: ./start.sh

set -euo pipefail

AGENTS_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPOSE_FILE="$AGENTS_DIR/docker-compose.yml"

log()  { printf '%s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

require_macos() {
  [[ "$(uname -s)" == "Darwin" ]] || fail "dieses Script unterstützt nur macOS"
}

ensure_brew() {
  if command -v brew >/dev/null 2>&1; then
    return
  fi
  fail "Homebrew fehlt. Installieren: https://brew.sh"
}

docker_ready() {
  command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1
}

compose_ready() {
  docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1
}

ensure_docker_stack() {
  if docker_ready && compose_ready; then
    log "Docker ist bereit."
    return
  fi

  ensure_brew
  log "Docker nicht bereit — installiere/aktualisiere via Homebrew: colima, docker, docker-compose"
  brew install colima docker docker-compose

  if ! command -v colima >/dev/null 2>&1; then
    fail "colima konnte nicht installiert werden"
  fi

  if ! colima status 2>/dev/null | grep -qi 'Running'; then
    log "Starte Colima…"
    colima start
  else
    log "Colima läuft bereits."
  fi

  docker_ready || fail "Docker-Daemon antwortet nicht (Colima/Docker prüfen)"
  compose_ready || fail "docker compose / docker-compose nicht gefunden"
  log "Docker ist bereit."
}

ensure_env() {
  if [[ ! -f "$AGENTS_DIR/.env" ]]; then
    if [[ -f "$AGENTS_DIR/.env.example" ]]; then
      cp "$AGENTS_DIR/.env.example" "$AGENTS_DIR/.env"
      log "`.env` aus `.env.example` angelegt — bitte HOST_PROJECTS und Keys anpassen."
    else
      fail "keine .env und keine .env.example gefunden"
    fi
  fi
}

load_env() {
  if [[ -f "$AGENTS_DIR/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "$AGENTS_DIR/.env"
    set +a
  fi
}

hermes_enabled() {
  case "${HERMES:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

# Opt-in Hermes via compose profile when HERMES=1 in .env

ensure_data_dirs() {
  mkdir -p \
    "$AGENTS_DIR/data/cursor" \
    "$AGENTS_DIR/data/cursor-config" \
    "$AGENTS_DIR/data/pi" \
    "$AGENTS_DIR/data/claude" \
    "$AGENTS_DIR/data/clipboard" \
    "$AGENTS_DIR/data/cliproxy/auths"
  if hermes_enabled; then
    mkdir -p "$AGENTS_DIR/data/hermes"
  fi
  # Legacy empty file mount blocked Claude auth writes — remove if present
  if [[ -f "$AGENTS_DIR/data/claude.json" ]]; then
    rm -f "$AGENTS_DIR/data/claude.json"
  fi
}

# Generate CLIPROXY_API_KEY if missing; write data/cliproxy/config.yaml once.
ensure_cliproxy() {
  load_env

  if [[ -z "${CLIPROXY_API_KEY:-}" ]]; then
    CLIPROXY_API_KEY="$(openssl rand -hex 32)"
    {
      printf '\n'
      printf '# CLIProxyAPI (Claudex) — auto-generated by start.sh\n'
      printf 'CLIPROXY_API_KEY=%s\n' "$CLIPROXY_API_KEY"
    } >> "$AGENTS_DIR/.env"
    log "CLIPROXY_API_KEY generiert und in .env geschrieben."
  fi

  local config="$AGENTS_DIR/data/cliproxy/config.yaml"
  if [[ ! -f "$config" ]]; then
    if [[ -f "$AGENTS_DIR/cliproxy/config.example.yaml" ]]; then
      sed "s/replace-with-CLIPROXY_API_KEY/${CLIPROXY_API_KEY}/" \
        "$AGENTS_DIR/cliproxy/config.example.yaml" > "$config"
    else
      cat > "$config" <<EOF
host: ""
port: 8317
auth-dir: "/root/.cli-proxy-api"
api-keys:
  - "${CLIPROXY_API_KEY}"
debug: false
EOF
    fi
    log "data/cliproxy/config.yaml angelegt."
  fi
}

start_agents() {
  ensure_env
  load_env
  ensure_data_dirs
  ensure_cliproxy

  if docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose -f "$COMPOSE_FILE")
  else
    COMPOSE=(docker-compose -f "$COMPOSE_FILE")
  fi

  if hermes_enabled; then
    log "Starte agents + cli-proxy-api + hermes…"
    "${COMPOSE[@]}" --profile hermes up -d --build
  else
    log "Starte agents + cli-proxy-api…"
    # Stop hermes if it was left running from a previous HERMES=1 session
    if docker ps --format '{{.Names}}' | grep -qx hermes; then
      log "HERMES=0 — stoppe hermes-Container…"
      "${COMPOSE[@]}" --profile hermes stop hermes >/dev/null 2>&1 || true
    fi
    "${COMPOSE[@]}" up -d --build
  fi

  log "Fertig. Beispiele: dagent | dpi | dclaude | dclaudex | agents-shell"
  log "Claudex OAuth (einmalig): agents cliproxy-login"
  log "Screenshot-Paste in Claude: Bridge startet mit dclaude (Ctrl+V, nicht Cmd+V)"
  if hermes_enabled; then
    log "Hermes: agents hermes-setup (einmalig) | agents hermes"
  fi
}

require_macos
ensure_docker_stack
start_agents
